### ISSUE TITLE
how to update Direct image

### ISSUE THREAD

**Issue by osamamohammed98** [luis901101/cloudflare#1]
<img width="630" alt="Screen Shot 2022-06-25 at 12 20 51 AM" src="https://user-images.githubusercontent.com/27555246/175683012-6dc0a56f-a590-4961-b302-2d77715bec98.png">

**Comment by luis901101** [comment]
Could you please give more details about what you specifically need?
For how to update an image you can check the package doc here [Update an image](https://pub.dev/packages/cloudflare#update-an-image) and [Official doc here](https://api.cloudflare.com/#cloudflare-images-update-image)

Just a side note: if what you want is to do an image update from a flutter app, you should take into account image update requires a cloudflare signed request I mean a request using `accountId` and `token`, so this should not be handled at app side but at backend side.

**Comment by osamamohammed98** [comment]
> Could you please give more details about what you specifically need? For how to update an image you can check the package doc here [Update an image](https://pub.dev/packages/cloudflare#update-an-image) and [Official doc here](https://api.cloudflare.com/#cloudflare-images-update-image)
> 
> Just a side note: if what you want is to do an image update from a flutter app, you should take into account image update requires a cloudflare signed request I mean a request using `accountId` and `token`, so this should not be handled at app side but at backend side.

The problem is what data is needed in MetaData ?

**Comment by luis901101** [comment]
Did you read the [Official doc](https://api.cloudflare.com/#cloudflare-images-update-image)? What you ask is explained there.
Metadata is a Map, no data is needed there, it is a map you can use to set any key:value pair of info you want to store with your image. 

> User modifiable key-value store. Can be used for keeping references to another system of record for managing images. No change if not specified.
"{\"meta\": \"metaID\"}"
