### ISSUE TITLE
Unable to upload meta Data to tus Stream

### ISSUE THREAD

**Issue by jitendravn** [luis901101/cloudflare#10]
I can't upload my additional meta data to tus 

final tusAPI = await cloudflare.streamAPI.tusStream(
      file: File(_selectedFile!.path),
      cache: TusMemoryCache(),
    );

**Comment by luis901101** [comment]
Hi @jitendravn I'm not sure what you mean?

The implementation of every `tus` stream function allows for metadata, these are:
```
- ... createTusDirectStreamUpload(...)
- ... tusDirectStreamUpload(...)
- ... tusStream(...)
``` 
Each function has a reference to the official Cloudflare documentation [Supported options in “Upload-Metadata”](https://developers.cloudflare.com/stream/uploading-videos/upload-video-file/#supported-options-in-upload-metadata)

You can easily check the implementation of each of these functions and you will see there the supported metadata properties.

Do you mean some specific metadata that is supported by Cloudflare and not by this package?
