### ISSUE TITLE
Error while build project

### ISSUE THREAD

**Issue by divyangdantani** [luis901101/cloudflare#2]
**Error:-** 
Launching lib\main.dart on DN2101 in debug mode...
lib\main.dart:1
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/cloudflare-1.3.0+11/lib/src/apiservice/stream_api.dart:832:36: Error: The getter 'name' isn't defined for the class 'MediaProcessingState'.
- 'MediaProcessingState' is from 'package:cloudflare/src/enumerators/media_processing_state.dart' ('/C:/flutter/.pub-cache/hosted/pub.dartlang.org/cloudflare-1.3.0+11/lib/src/enumerators/media_processing_state.dart').
package:cloudflare/…/enumerators/media_processing_state.dart:1
Try correcting the name to the name of an existing getter, or defining a getter or field named 'name'.
      status: status?.map((e) => e.name).join(','),

                                   ^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/cloudflare-1.3.0+11/lib/src/entity/cloudflare_stream_video.dart:328:44: Error: The getter 'name' isn't defined for the class 'ThumbnailFit'.
- 'ThumbnailFit' is from 'package:cloudflare/src/enumerators/thumbnail_fit.dart' ('/C:/flutter/.pub-cache/hosted/pub.dartlang.org/cloudflare-1.3.0+11/lib/src/enumerators/thumbnail_fit.dart').
package:cloudflare/…/enumerators/thumbnail_fit.dart:1
Try correcting the name to the name of an existing getter, or defining a getter or field named 'name'.

**Flutter Version :- 2.5.3**
**Code Editor VSCode**

please help me out ASAP, Thanks...

**Comment by luis901101** [comment]
This package depends on `Dart sdk: '>=2.14.0 <3.0.0'`, you must upgrade your Flutter version to latest or at least Dart version to one in the specified range.
