### ISSUE TITLE
Direct Creator Upload with Custom ID

### ISSUE THREAD

**Issue by sharpsaravanan** [luis901101/cloudflare#7]
Thank you for creating such an incredible repository,

"Direct Creator Upload with Custom ID"
https://developers.cloudflare.com/images/cloudflare-images/upload-images/direct-creator-upload/
![custom creator upload](https://github.com/luis901101/cloudflare/assets/62005270/922cc007-fb96-49e0-9d57-a73a40ecd9ba)

Please, Add this functionality in cloudflare.imageAPI.createDirectUpload or a new function.

**Comment by luis901101** [comment]
Hi, thanks.
**Create Direct Upload** and do a **Direct Upload**, both features are supported by this package, I encourage you to read the entire README.md
